import ast

from .models import step_to_dict

PY_TEMPLATE = r'''"""Auto-generated by Click Studio - plays a recorded sequence.

Requires: pip install pyautogui
Move the mouse into any screen corner to abort (pyautogui failsafe).
"""
import ctypes
import ctypes.wintypes
import os
import re
import subprocess
import time

import pyautogui

pyautogui.FAILSAFE = True
pyautogui.PAUSE = 0

LOOPS = 1

_SPECIAL = {
    "ENTER": "enter",
    "TAB": "tab",
    "SPACE": "space",
    "ESC": "esc",
    "DEL": "delete",
    "BACKSPACE": "backspace",
    "UP": "up",
    "DOWN": "down",
    "LEFT": "left",
    "RIGHT": "right",
    "HOME": "home",
    "END": "end",
    "PGUP": "pageup",
    "PGDN": "pagedn",
    "INSERT": "insert",
}
_MODS = {"^": "ctrl", "!": "alt", "+": "shift", "#": "win"}

STEPS = @STEPS@


def _parse(spec):
    out = []
    mods = []
    i = 0
    while i < len(spec):
        ch = spec[i]
        if ch in _MODS:
            mods.append(_MODS[ch])
            i += 1
            continue
        if ch == "{":
            j = spec.find("}", i)
            if j == -1:
                break
            name = spec[i + 1 : j].upper()
            key = _SPECIAL.get(name)
            if key is None and re.fullmatch(r"F\d+", name):
                key = name.lower()
            if key is None:
                mods = []
            else:
                out.append((tuple(mods), key))
                mods = []
            i = j + 1
            continue
        out.append((tuple(mods), ch))
        mods = []
        i += 1
    return out


def _send(spec):
    for mods, key in _parse(spec):
        if mods:
            pyautogui.hotkey(*mods, key, _pause=False)
        else:
            pyautogui.press(key, _pause=False)


def _window_action(hwnd, action):
    WM_CLOSE = 16
    if action == "close":
        ctypes.windll.user32.PostMessageW(hwnd, WM_CLOSE, 0, 0)
    elif action == "minimize":
        ctypes.windll.user32.ShowWindowAsync(hwnd, 6)
    elif action == "maximize":
        ctypes.windll.user32.ShowWindowAsync(hwnd, 3)
    elif action == "restore":
        ctypes.windll.user32.ShowWindowAsync(hwnd, 9)
    elif action == "focus":
        if ctypes.windll.user32.IsIconic(hwnd):
            ctypes.windll.user32.ShowWindowAsync(hwnd, 9)
            time.sleep(0.05)
        ctypes.windll.user32.keybd_event(18, 0, 0, 0)
        ctypes.windll.user32.SetForegroundWindow(hwnd)
        ctypes.windll.user32.keybd_event(18, 0, 2, 0)


def _find_window(title):
    needle = title.strip().casefold()
    if not needle:
        return None
    result = []
    proto = ctypes.WINFUNCTYPE(ctypes.wintypes.c_bool, ctypes.wintypes.HWND, ctypes.wintypes.LPARAM)

    def cb(hwnd, lparam):
        if not ctypes.windll.user32.IsWindowVisible(hwnd):
            return True
        n = ctypes.windll.user32.GetWindowTextLengthW(hwnd)
        if n <= 0:
            return True
        buf = ctypes.create_unicode_buffer(n + 1)
        ctypes.windll.user32.GetWindowTextW(hwnd, buf, n + 1)
        pid = ctypes.wintypes.DWORD()
        ctypes.windll.user32.GetWindowThreadProcessId(hwnd, ctypes.byref(pid))
        if pid.value == os.getpid():
            return True
        if needle in buf.value.casefold():
            result.append(hwnd)
            return False
        return True

    ctypes.windll.user32.EnumWindows(proto(cb), 0)
    return result[0] if result else None


def _play(steps):
    for s in steps:
        time.sleep(max(0, int(s.get("delay", 0))) / 1000.0)
        kind = s.get("type")
        if kind == "mouse":
            clicks = max(1, int(s.get("clicks", 1)))
            btn = s.get("button", "left")
            pyautogui.moveTo(int(s.get("x", 0)), int(s.get("y", 0)), duration=0.05, _pause=False)
            for c in range(clicks):
                pyautogui.mouseDown(button=btn, _pause=False)
                time.sleep(max(0, int(s.get("hold", 60))) / 1000.0)
                pyautogui.mouseUp(button=btn, _pause=False)
                if c < clicks - 1:
                    time.sleep(0.06)
        elif kind == "key":
            cnt = max(1, int(s.get("count", 1)))
            ivl = max(0, int(s.get("interval", 100)))
            for c in range(cnt):
                _send(str(s.get("key", "")))
                if c < cnt - 1:
                    time.sleep(ivl / 1000.0)
        elif kind == "sleep":
            time.sleep(max(0, int(s.get("duration", 0))) / 1000.0)
        elif kind == "cmd":
            subprocess.run(str(s.get("command", "")), shell=True)
        elif kind == "window":
            hwnd = _find_window(str(s.get("title", "")))
            if hwnd:
                _window_action(hwnd, str(s.get("action", "focus")))


if __name__ == "__main__":
    try:
        loops = max(1, int(LOOPS))
        for n in range(loops):
            _play(STEPS)
        print("Finished - %d loop(s)" % loops)
    except KeyboardInterrupt:
        print("Stopped")
'''


def build_sequence_script(steps) -> str:
    return PY_TEMPLATE.replace("@STEPS@", repr([step_to_dict(s) for s in steps]))


def steps_payload_from_script(text: str) -> list:
    tree = ast.parse(text)
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign):
            targets = node.targets
        elif isinstance(node, ast.AnnAssign) and node.value is not None:
            targets = [node.target]
        else:
            continue
        for t in targets:
            if isinstance(t, ast.Name) and t.id == "STEPS":
                val = ast.literal_eval(node.value)
                if isinstance(val, list):
                    return val
    raise ValueError("STEPS definition not found in script")
